### ISSUE TITLE
Reading hangs when using mpi for 16 processors

### ISSUE THREAD

**Issue by wjlei1990** [SeismicData/pyasdf#1]
Hi Lion,

I got pyflex hang up when using asdf data on rhea(Oak Ridge machine). The program runs to a point and stops at a certain trace(As far as I noticed, it stops at the same traces everytime).

The command I used to run the code is:
mpiexec -n 16 python parallel_pyflex.py

The problem only happens when I use 16 processors(using mpi). For 2, 4, 8 processors, the program works.

The parallel_pyflex.py uses the function: process_two_files_without_parallel_output(ds1, ds2). The script is almost the same as this one: https://github.com/krischer/InversionWorkflowExample/blob/master/parallel_pyflex.py

Might be 2 reasons:
1) the file is corrupted. So I need to do more test, to see if this happens on more files. But the wired thing is the same file works on 2 to 8 processors.
2) the pyasdf is buggy.

I will post more updates later after doing more test.

**Comment by krischer** [comment]
Is this still an issue? If yes: is there a way to give me access to a machine with this problem so that I can have a look?

**Comment by wjlei1990** [comment]
Hi Lion,

I was a little busy last week.

I will try it afterwards.

Best,
Wenjie
----------------------------------------------------
 Graduate student in Geophysics
 Princeton University | Guyot Hall 309
 Phone: 609-937-4659
________________________________
