### ISSUE TITLE
mpi4py (2.0.0) is not compatible with h5py (2.5.0)

### ISSUE THREAD

**Issue by chukren** [SeismicData/pyasdf#11]
The mpi4py.mpi_c has changed to mpi4py.libmpi, so cause the imcompatibility. Current solution is switch to the old version of mpi4py (1.3.x) or make changes in h5py.  See discussion at https://github.com/rdhyee/h5py/commit/f2e3f132fdc1c2308b74e8428c063ac6a8118439#diff-c9e1291e5e01f0f5e0a484dccaf67cf6L28
﻿

**Comment by krischer** [comment]
Thanks for letting us know. This has to be fixed on the h5py side. I'll put a link to this issue in the `pyasd` docs.

**Comment by wjlei1990** [comment]
Hi Lion,

That's is the issue we found recently when we use pip to install mpi4py. I think they recently put the version 1.3.1 to 2.0.0 but h5py is not aware of that.

Should we put a issue on h5py website?

**Comment by krischer** [comment]
> Should we put a issue on h5py website?

If they are not aware of it then definitely!

**Comment by wjlei1990** [comment]
Hi Lion,

I saw the h5py group just update the h5py to be compatible with mpi4py 2.0.0.

See here please.
https://github.com/h5py/h5py/commit/364a77403199087168786234554f459e7d985063

Can you conform at you end that it is running?

**Comment by krischer** [comment]
I tried and this works with pyasdf :-)
