### ISSUE TITLE
bug introduced in recent commit

### ISSUE THREAD

**Issue by wjlei1990** [SeismicData/pyasdf#13]
Hi Lion,

When I am using pyasdf to process observed data(with mpi), I found the asdf_data_set.process() function won't return correctly. To be more specific, every processor runs thorough the process() function but can not return to the upper level.

I did some research and found the bug is introduced in the commit: https://github.com/SeismicData/pyasdf/commit/c75d65b22340a369022112e0f2c2a67b10970dae

The commit before this is fine.

We have something setup on bitbucket but it is private now. @mpbl Is it OK to give Lion permission to the repocitory(source_inversion_wf) so he can run our example test case?

We have everything setup there(bitbucket repo). So after downloading it, you will be able to run some tests and you will see the bugs.

**Comment by wjlei1990** [comment]
If the pretty output is too complicated to implement, I think we can just take it out for now.

**Comment by krischer** [comment]
It's probably some reference thingy.

If you give me access to something I can run I'll fix the bug. Thanks!

**Comment by wjlei1990** [comment]
I think you have the permission now.

Could you confirm, Lion?

**Comment by krischer** [comment]
It was indeed a reference problem. I think the traceback and stack I collected to be able to print the nice error message kept a reference to some part in the HDF5 file and thus it got stuck...

With 484f41f211fa5d6c753e793c5d215d1cb30124c7 I can run your example and it finishes fine. 

Let me know if you encounter more of these issues. It's really hard to search and test these.
