### ISSUE TITLE
validate() not working as we expect

### ISSUE THREAD

**Issue by wjlei1990** [SeismicData/pyasdf#14]
I think the validate() is not working as we expect it to be.

In asdf_data_set.py, Line 1224 - 1239.
```
 for station_id in dir(self.waveforms):
            station = getattr(self.waveforms, station_id)
            contents = dir(station)
            if not contents:
                continue
            if "StationXML" not in contents and contents:
                print("No station information available for station '%s'" %
                      station_id)
                summary["no_station_information"] += 1
                continue
            contents.remove("StationXML")
            if not contents:
                print("Station with no waveforms: '%s'" % station_id)
                summary["no_waveforms"] += 1
                continue
            summary["good_stations"] += 1
```
When you check for waveform, you remove the "StationXML" and check if there are attributes left. But as the evolving of pyasdf, this is no longer true. Once you have StationXML, you will also have "channle_coordinates" and "coordinates".

A more strict way to check waveform is loop over attributes ans see if there is one same as type as "obspy.core.stream.Stream"

**Comment by krischer** [comment]
Good catch. I rewrote parts of the function to take into account new developments and added a test for it so it should no longer break. Thanks for reporting!
