### ISSUE TITLE
check file existance

### ISSUE THREAD

**Issue by wjlei1990** [SeismicData/pyasdf#16]
Hi,

We recently ran into this issues on openmpi(gcc) in ubuntu system.

In asdf_data_set.py, Line 1409-1411:
```
        if os.path.exists(output_filename):
            msg = "Output file '%s' already exists." % output_filename
            raise ValueError(msg)
```
The check is running on every processors. So the case is: not everytime the processors will reach this point at the same time. If one processor is running very fast and already created the file, the other processors will raise an error.

Somehow, it works on openmpi(cray-gcc) but not working on openmpi(gcc) in ubuntu(Norbert found this problem when he is trying our workflow).  I think there might be some implementation difference between these two.

My suggestion would be either of the following:
  * only check on master processor
  * put a mpi barrier after this block to make sure every processor reach this point at the same time.

@mpbl

**Comment by krischer** [comment]
Nice catch. Should be fixed now.

Additionally it now no longer gets a list of all stations on all ranks but only on the first rank which should be a bit faster.

Let me know if there are any other issues - pyasd unfortunately has no tests for the mpi part - I really need to cook something up I guess.
