### ISSUE TITLE
why mode='a' is preferred?

### ISSUE THREAD

**Issue by wjlei1990** [SeismicData/pyasdf#24]
Just curious. I noticed in asdf_data_set.py, in `__init__()`, you wrote:
```
        :param mode: The mode the file is opened in. Passed to the
            underlying :class:`h5py.File` constructor. pyasdf expects to be
            able to write to files for many operations so it might result in
            strange errors if a read-only mode is used. Nonetheless this is
            quite useful for some use cases as long as one is aware of the
            potential repercussions.
        :type mode: str
```

Not sure what you mean exactly here...

For example, for the data processing procedure, I will read the raw data and write the processed data into a new file. For the window selection, I will read the observed data and synthetic data, and write out windows. None of them modify the input asdf file. So is it safe to use `mode='r'` or still better to use `mode='a'`?

**Comment by krischer** [comment]
Yes of course. If you only read I would strongly recommend to use `mode="r"`. The documentation should probably be a bit clearer in the documentation. You only need to open it in a writable mode if you modify the file.

**Comment by wjlei1990** [comment]
Got it. Thanks.
