### ISSUE TITLE
Possible to be more flexible on stationxml side?

### ISSUE THREAD

**Issue by wjlei1990** [SeismicData/pyasdf#27]
Hi Lion,

I am collaborating with Yanhua and another seismologist working on China tomography.

One problem that prevents us using pyasdf is that they don't have STATIONXML file.(Sorry to mention that, but the China data is not available online....). They only have Pole and Zero files.

Actually, I think a lot of seismologists has this issue right now. Not all of us are using STATIONXML. So my question is: 

To attract those "old" users, should we consider adding the capability of add PZ files or RESP files?

**Comment by jas11** [comment]
Hi Wenjie,

Why not convert the poles and zeros to StationXML as Youyi has done and I did for some custom stations that didn't provide StationXML?

Also "old" users will die off and so I don't think attracting them should be our goal.

Best,
James

________________________________

**Comment by wjlei1990** [comment]
Oops, I didn't know that.

I will ask you...

Thanks, James.

**Comment by wjlei1990** [comment]
After a short dicsussion with James and Youyi, I don't think we have a solution now to convert pz files now. I am going to reopen this issue and see what's is Lion's opinion.

**Comment by krischer** [comment]
You will have to convert whatever you have to StationXML. Why is it not an option to do that? If its only poles and zeros it should be fairly simple.

It makes no sense to support two separate formats for the same information within ASDF. We defined the format to no longer have multiple ways of storing the same things.

**Comment by wjlei1990** [comment]
Do you have any examples or scripts, showing how to convert from pz files into StationXML?

**Comment by krischer** [comment]
Here is a function that does the inverse (it goes from ObsPy Inventory object to a sacpz file):

https://github.com/obspy/obspy/blob/c43345f1dd5510ebf2d7e46be4286363631dc25c/obspy/io/sac/sacpz.py#L22-L98

and

https://github.com/obspy/obspy/blob/c43345f1dd5510ebf2d7e46be4286363631dc25c/obspy/core/inventory/response.py#L1342-L1363

We so far had no need to go from sacpz to ObsPy object but it should be pretty simple. You essentially have to create this object:

http://docs.obspy.org/packages/autogen/obspy.core.inventory.response.PolesZerosResponseStage.html#obspy.core.inventory.response.PolesZerosResponseStage

and the corresponding parent object (but this is easy - i can help you with this).

Once it is done you just call `inventory.write()` and you have a StationXML file which pyasdf is happy to work with.

**Comment by wjlei1990** [comment]
Great! I will take a look during the weekend!

**Comment by wjlei1990** [comment]
Hi Lion,

I have created a git repo here: https://github.com/wjlei1990/parse_pz

I have added some sample test data. I will add some more stuff later.

To create the inventory object, there are soooo many paramters which I am not quite sure...I think I need your help there.

Let me write a pz files parser and I will let you know.
