### ISSUE TITLE
_sync_metadata() impacts the performace

### ISSUE THREAD

**Issue by wjlei1990** [SeismicData/pyasdf#28]
Hi Lion,

I recently found that running multiple processing jobs at the same time greatly increase the running time. For example, if only running one job, job could be done in 25 sec. If running 5 jobs at the same time, the job will last for 90 sec. If running 20 jobs at the same time, it becomes really really slow. 

After some simple investigation, I found the problem comes from the `_sync_metadata()` method in `asdf_data_set.py`. I will do more investigation and let you know the the result.

**Comment by krischer** [comment]
Would be great :-)

Keep in mind that its not worth it tto parallelize for something that takes 25 seconds. There is fairly large constant cost and each additional core will also add some more initialization cost.

What's definitely worth trying it to install the latest hdf5 and h5py versions (1.10 and 2.6, respectively) and set `libver` to `latest` in the `h5py.File` call in the `__init__()` method of the dataset object. That might result in quite some speed increase.

http://docs.h5py.org/en/latest/high/file.html#version-bounding

**Comment by wjlei1990** [comment]
I think I have located it, it is here: https://github.com/wjlei1990/pyasdf/blob/master/pyasdf/asdf_data_set.py#L1099

```
info = {
            "station_name": station_name,
            "data_name": group_name,
            "dataset_creation_params": {
                "name": data_name,
                "shape": (trace.stats.npts,),
                "dtype": trace.data.dtype,
                "compression": self.__compression[0],
                "compression_opts": self.__compression[1],
                "shuffle": self.__shuffle,
                "fletcher32": fletcher32,
                "maxshape": (None,)
            },
            "dataset_attrs": {
                # Starttime is the epoch time in nanoseconds.
                "starttime":
                    int(round(trace.stats.starttime.timestamp * 1.0E9)),
                "sampling_rate": trace.stats.sampling_rate
            }
        }
```

The `maxshape` is set to be (None, ), which means the size is unlimited. When 20 jobs is defining such a unlimited thing on the disk at the same time, I am guessing it is slowing the whole thing down. When I comment the `maxshape` out and it run 3-5 times faster.

I guest this problem only get severe with increasing number of jobs. For example, if I want to have 100 events running at the same time and each job is defining its maxshape, it is getting more and more slow.

**Comment by krischer** [comment]
Interesting. If `maxshape` is set `(None, )`, it means that the dataset can be resized to arbitrary dimensions - it does not really write anything to the file. I have no clue why metadata speed is affected by that. I just ran some tests and I don't really see a big difference. Its a bit faster if I comment the `maxshape` line but not much and IMHO the advantage of being able to resize the data is worth that tradeoff. But in your case its clearly much worse.

Can you send me the files + scripts you processed so I can try to reproduce that behavior on one of our machines?

Can you please also paste the output of `python -c "import pyasdf; pyasdf.print_sys_info()"`?

**Comment by wjlei1990** [comment]
I know, if we can keep flexibility with performance, that would be great. I am guessing if we set `maxshape=(None, )`, it might take some extra resource to achieve the goal. I think if you just run on one file, you won't see much difference. It only occurs when  we scale it up to processing like 10 files at the same time.

I will work with Matthieu in the following weeks to see if we can optimize some parts of the code.

I will prepare your some files on sdf@clover.princeton.edu. I will let you know when I am done with data.

Here is the output of `sys_info`:
```
[lei@rhea-login7g ~]$ python -c "import pyasdf; pyasdf.print_sys_info()"
--------------------------------------------------------------------------
An MPI process has executed an operation involving a call to the
"fork()" system call to create a child process.  Open MPI is currently
operating in a condition that could result in memory corruption or
other system errors; your MPI job may hang, crash, or produce silent
data corruption.  The use of fork() (or system() or other calls that
create child processes) is strongly discouraged.  

The process that invoked fork was:

  Local host:          rhea-login7g (PID 77657)
  MPI_COMM_WORLD rank: 0

If you are *absolutely sure* that your application will successfully
and correctly survive a call to fork(), you may disable this warning
by setting the mpi_warn_on_fork MCA parameter to 0.
--------------------------------------------------------------------------
pyasdf version 0.1.x
===============================================================================
CPython 2.7.11, compiler: GCC 4.4.7 20120313 (Red Hat 4.4.7-1)
Linux 2.6.32-573.18.1.el6.x86_64 64bit
Machine: x86_64, Processor: x86_64 with 32 cores
===============================================================================
HDF5 version 1.8.11, h5py version: 2.6.0
MPI: Open MPI, version: 1.8.4, mpi4py version: 2.0.0
Parallel I/O support: True
Problematic multiprocessing: False
===============================================================================
Other_modules:
	lxml: 3.5.0
	numpy: 1.10.4
	obspy: 0.10.2
	prov: 1.4.0
	scipy: 0.17.0
```
