### ISSUE TITLE
File naming of test dataset results in error during clone on Windows

### ISSUE THREAD

**Issue by calum-chamberlain** [SeismicData/pyasdf#34]
I should preface this by saying, I'm not sure if you support Windows, or want to support it, but I have run into a small issue cloning the repository (as the suggested install method).  Files:
- pyasdf/tests/data/small_sample_data_set/AE.113A..BH*.xml
- pyasdf/tests/data/small_sample_data_set/TA.POKR..BH*.xml
cannot be created on windows, because of the `*` in the file-name.  Do you know of anyway around that, or can the files be re-named?

I am running on Windows 7, Python 2.7, git 2.10.1.windows.1.

Main reason for asking is I would like to use pyASDF for EQcorrscan (for storing templates and detections with waveforms alongside catalogs and meta-data from processing) and have run in to issues running tests on appveyor.

The full error message is:
```bash
$ git clone https://github.com/SeismicData/pyasdf.git
Cloning into 'pyasdf'...
remote: Counting objects: 2391, done.
remote: Compressing objects: 100% (42/42), done.
remote: Total 2391 (delta 23), reused 0 (delta 0), pack-reused 2349
Receiving objects: 100% (2391/2391), 4.46 MiB | 1017.00 KiB/s, done.
Resolving deltas: 100% (1618/1618), done.
error: unable to create file pyasdf/tests/data/small_sample_data_set/AE.113A..BH*.xml: Invalid argument
error: unable to create file pyasdf/tests/data/small_sample_data_set/TA.POKR..BH*.xml: Invalid argument
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
```

**Comment by QuLogic** [comment]
I think it's just a convenient name; it's just test data after all. Probably shouldn't be any issue renaming them.

**Comment by krischer** [comment]
Renamed the files in 0697e0535f1592da5d4938df0c6cbaf2bb71ffe3. Let me know if this does not work. I'm also trying to setup appveyor for this repository.

This should definitely work for windows - a file format that cannot be opened everywhere is kind of useless.

**Comment by krischer** [comment]
If somebody want to help debug appveyor: https://ci.appveyor.com/project/krischer/pyasdf

No clue why it does not work - It does exactly the same as the obspy appveyor config but does not even pass the initial setup phase.

**Comment by krischer** [comment]
Alright - I got it more or less working. Now there is a multiprocessing issue left on windows but that might be interesting to debug.

**Comment by krischer** [comment]
Last message from my side: Windows should now be good to go and tests pass on appveyor.
