### ISSUE TITLE
Put all the packages together

### ISSUE THREAD

**Issue by wjlei1990** [SeismicData/pyasdf#37]
Hi Lion,

There are some people want to use our tools, including pyflex, pyadjoint, [pytomo3d](https://github.com/wjlei1990/pytomo3d), pyasdf and so on. I am thinking about moving all these packages to one place so people could easily find those resource at once. What do you think about it? If so, what kind of "one place" would be suitable?

Because now all the packages are more or less hosting in quite a few of places, when I introduce these tools to people, they get confused.

@mpbl

**Comment by krischer** [comment]
Hey Wenjie,

`pyasdf` and `pyflex` are on pypi so people can just install these with `pip install X`. `pyasdf` is additionally on conda-forge so `conda install -c conda-forge pyadsf` works as well. If you package up your other packages in the same manner it should be easy to install for everyone. Thus most packages can just be treated as external dependencies and they are "tied" together by using `pip` or `conda` which people need to do in any case for the other dependent modules. Additionally you could create a web site/wiki that documents the inversion workflow and how to to install the necessary pieces.

Also the use of `pyadsf` is not only for FWI so I would prefer if it stays in this github organization where all the ASDF things are collected.

Cheers!

**Comment by krischer** [comment]
Hi Matthieu,

I see. I guess a `princeton-seismology` group might be useful for that purpose - I don't think it would fit into the `SeismicData` organization.

We also own the `seismology` Github group (http://github.com/seismology) but not a lot is under it as of now. You would be welcome to join the group.

Cheers!

Lion

**Comment by mpbl** [comment]
Hi, Lion,

Thanks for your advices.
After talking among us, we'll go with ```computational-seismology```.

Cheers!
Matthieu
