### ISSUE TITLE
Fast extraction of event location data for all waveforms

### ISSUE THREAD

**Issue by nmancinelli** [SeismicData/pyasdf#38]
Hi @krischer!  I have ASDF files with ~100 events and ~100 stations.  I try to make a list of the source, receiver location information of all waveforms using the following loop:

```python
import pyasdf
from obspy.clients.iris import Client

client = Client()

ds = pyasdf.ASDFDataSet(file)

for event in ds.events:
    origin = event.preferred_origin() or event.origins[0]

    for station in ds.ifilter(ds.q.event == event, ds.q.channel == 'BHZ'):
        result = client.distaz(station.coordinates["latitude"], station.coordinates["longitude"], origin.latitude,
                               origin.longitude)
        deg = result['distance']
        baz = result['backazimuth']

        iwav += 1
        print('%10d %15.4f %15.4f %15.4f %15.4f %6.1f %6.1f'
          % (iwav, origin.latitude, origin.longitude,
             station.coordinates["latitude"], station.coordinates["longitude"],
             deg, baz))
```

The code works, but the event query is very slow.  Do you know of a better way?  Perhaps a query and loop over all BHZ traces would be faster, but in that case I don't know how to get the origin information for each trace.

**Comment by krischer** [comment]
Hi!

I suspect that the `client.distaz` call is the slow part as this will query a web service. Note that we document local alternatives to some IRIS web services here: http://docs.obspy.org/packages/obspy.clients.iris.html#local-alternatives

In your case you should probably just use this function: http://docs.obspy.org/packages/autogen/obspy.geodetics.base.gps2dist_azimuth.html

Please also install `geographiclib` as ObsPy will then use their implementation which is stable also for antipodal points.

Another thing that might be slow is accessing `ds.events` as `pyasdf` at this time will load the QuakeML file inside the ASDF file and parse to an ObsPy `Catalog` object. This parsing can be fairly slow. If that is the limiting factor for your application please let me know - I could provide a faster alternative to get the event ids which would be fairly easy.

**Comment by krischer** [comment]
one more thing: `station.coordinates` will extract the coordinates from the StationXML file each time you call it! best store it to a temporary variable in the loop before accessing it multiple times.

This could of course also be buffered by `pyadsf` but this becomes pretty tricky as it might have been modified in-between two accesses and HDF5 has AFAIK no concept of storing the last modified date per dataset.

**Comment by nmancinelli** [comment]
Thanks for this.  The code is much faster after making your suggested changes.  Calling ```ds.events``` takes anywhere between 0.5 and 2.0 s for my files.  It is only called once per file and I only have ~30 files (1 per year of data), so it's not a significant bottleneck.

**Comment by krischer** [comment]
Yea that is about what I would have suspected and as long as no one needs it to be any faster I'd leave it as it is right now.

You probably also don't need to also filter for the channel - just filtering by event should only give you stations that have data from that event. 

Also I think it might be faster like this - its a bit manual but it avoids multiple loops over the file (the `.ifilter()` method always loops over the whole file):

```python
import pyasdf

with pyasdf.ASDFDataSet("./asdf_example.h5", mode="r") as ds:
    # Get dictionary of resource_id -> Lat/Lng pairs
    events = {
        str(e.resource_id): [(e.preferred_origin() or e.origins[0]).get(i)
                             for i in ["latitude", "longitude"]]
        for e in ds.events}

    # Loop over all stations.
    for s in ds.waveforms:
        try:
            coords = s.coordinates
        except pyasdf.ASDFException:
            continue

        # Get set of all event ids. Ugly but there currently is no nice
        # API for this.
        group = s._WaveformAccessor__hdf5_group
        event_ids = list({group[i].attrs.get("event_id", None) for i in s.list()})
        event_ids = [i.decode() for i in event_ids if i]

        for e_id in event_ids:
            if e_id not in events:
                continue
            # Do your thing:
            print("%.2f %.2f %.2f %.2f" % (events[e_id][0],
                                           events[e_id][1],
                                           coords['latitude'],
                                           coords['longitude']))
```

**Comment by nmancinelli** [comment]
wow -- this is much faster.  thank you!  maybe it's worth making event_id more cleanly accessible from the waveform accessor so that newcomers like me can easily get to it.  But I'll leave that decision to you since the code snippet above works great for my purposes.

**Comment by krischer** [comment]
Done in #39. There is now also a short example snippet in the documentation demonstrating how to use it: http://seismicdata.github.io/pyasdf/examples/source_receiver_geometry.html
