### ISSUE TITLE
numpy should probably be a dependency

### ISSUE THREAD

**Issue by petrrr** [SeismicData/pyasdf#4]
This is only a very minor issue. I realize that numpy is directly imported several times:
```
pyasdf/asdf_data_set.py:import numpy as np
pyasdf/tests/test_asdf_data_set.py:import numpy as np
pyasdf/utils.py:import numpy as np
```
So it probably should become a formal dependency.

**Comment by krischer** [comment]
Fair enough. Its already a dependency of multiple dependencies, but I'll add it.
