### ISSUE TITLE
question regarding station names

### ISSUE THREAD

**Issue by rmodrak** [SeismicData/pyasdf#40]
ASDFDataSet.WaveformAccessor uses a station/network/channel naming convention, but not all data sets include this type of information.   For example, obspy.read leaves these attributes empty when reading from certain formats, such as SeismicUnix.  Any suggested workarounds?  Would you suggest manually setting the 'station' attribute for each trace with, say, the trace number index?

Any  suggestions would be greatly appreciatated.  Thanks, Ryan

**Comment by krischer** [comment]
Yes - I would manually set it.

Soonish (hopefully) the FDSN will expand the semantics of the network/station/location/channel identifers quite a bit to for example make it more suitable for active source and large-N deployments. At that points ASDF naturally just gains these. I actually don't see another option.

Note that ASDF  currently limits the maximum length of the identifiers to 2 (network), 5 (station), 2 (location), and 3 (channel). But `pyasdf` ignores these limits for practical reasons - they are only enforced in the validator and the specification.

**Comment by rmodrak** [comment]
Thanks very much!
