### ISSUE TITLE
two-way conversion :  sac <--> asdf    

### ISSUE THREAD

**Issue by rmodrak** [SeismicData/pyasdf#41]
Some of our tools work on sac files, others work on ASDF files, so I'd like to be able to convert forward and backward without any loss of metadata.

`pyasdf/scripts/sac2asdf.py` does not preserve `stats.sac` dictionaries, so I wrote a new version that does:  https://github.com/rmodrak/asdf_converters/blob/master/asdf_converters/sac2asdf.py

this new script constructs a dictionary `{(original_sac_filename: trace.stats.sac) for trace in stream}`, dumps it into a dill virtual file that is then saved as an ASDF auxiliary data file.

What remains is to devise a mapping between original_sac_filenames <--> ASDF waveforms.  I see no easy way of doing this using the existing ASDF API.  `ASDFDataSet.get_waveforms` comes close, but I think there ought to be a simpler way.  

Am I missing something?  Any advice would be greatly appreciated.

**Comment by krischer** [comment]
I'm not necessarily too fond on such a tool but I can see how this would be hugely useful in practice especially when transitioning workflows to ASDF. So if its okay with you I might even replace the existing `pyasdf/scripts/sac2asdf.py` with your script and its inverse once it finalized.

> this new script constructs a dictionary {(original_sac_filename: trace.stats.sac) for trace in stream}, dumps it into a dill virtual file that is then saved as an ASDF auxiliary data file.

Maybe consider dumping a JSON string to the auxiliary data? Then there at least is some chance to also read it with a non-Python tool.

> What remains is to devise a mapping between original_sac_filenames <--> ASDF waveforms. I see no easy way of doing this using the existing ASDF API. ASDFDataSet.get_waveforms comes close, but I think there ought to be a simpler way.

You could use the waveform labels to store the filenames: http://seismicdata.github.io/pyasdf/of_tags_and_labels.html

Another option would be to store the HDF5 path for each waveform in the dumped dictionary.

**Comment by rmodrak** [comment]
I share your mixed feelings, but as you were saying, it may be a practical
necessity until more applications natively support ASDF.

Good suggestions, let me respond further after I've looked into them a bit
more.
