### ISSUE TITLE
ASDFDataSet.tags attribute

### ISSUE THREAD

**Issue by malcolmw** [SeismicData/pyasdf#46]
Hi, Lion,

I think adding a _tags_ attribute to the ASDFDataSet class would useful. It would provide the user with quick access to a list of all available tags in the dataset, and could be used to drive processing in some cases.

I would be happy to contribute this, but want to conform to any standards and recommendations you might have. Do you have any standards for contributing code? or recommendations for how to add this particular feature?

Grace and peace,
Malcolm

**Comment by krischer** [comment]
Hi Malcolm,

this is a one-liner but I'm in favor of adding a `tags` attribute to the `ASDFDataSet` class. Anything that makes live easier is a good thing :-)

```python
set(itertools.chain.from_iterable(i.get_waveform_tags() for i in ds.waveforms))
```

I'd be happy to implement it but I'm even more happy if new people contribute to the code so please go for it.

In terms of standards: Just format the code according to whatever the latest `flake8` demands (this is enforced during the CI or if you run the tests with `flake8` installed), add at least one test for it, and make sure the tests still pass. The CI will run the tests on all supported Python versions/operating systems so there is usually no need to do this yourself.

Cheers!

**Comment by malcolmw** [comment]
Thanks :)

I was kind of thinking and hoping that this would be a simple update - a good first contribution. I'll add it and submit a PR.

**Comment by krischer** [comment]
Done in #47.
