### ISSUE TITLE
Bug found on job spliting

### ISSUE THREAD

**Issue by wjlei1990** [SeismicData/pyasdf#6]
Hi Lion,

A few month a ago, I mentioned a bug as pyasdf that it failed spliting job on 16 processor. I think I have located it somehow. It is related to how you split the job.

Please check line 1242-1252 in asdf_data_set.py:
+++++++++++++++++++++++++++++++++
```
        # Divide into chunks, each rank takes their corresponding chunks.
        def chunks(l, n):
            """
            Yield successive n-sized chunks from l.
            From http://stackoverflow.com/a/312464/1657047
            """
            for i in range(0, len(l), n):
                yield l[i:i+n]

        chunksize = int(math.ceil(len(usable_stations) / self.mpi.size))
        all_chunks = list(chunks(usable_stations, chunksize))
```
++++++++++++++++++++++++++++++++++
Let me make a example. If we have 164 streams and 16 processors. Based on the calculation, the chunksize will be 11 since you used math.ceil. Then the 15th processor will already consume all the jobs( 15 * 11 = 165 > 164). Thus, the len(all_chunks) = 15 and the 16th processor has nothing to take from all_chunks(invalid index). This kind of problem will always happen if the number of process is larger than the chunksize.

However, I think the current version of mpi4py doesn't handle error very well so the program hangs instead of quit.

I have written another piece of job splitting code to substitute the above chunk:
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
```  
     def chunks(l, nchunks):
            all_chunks = []
            # general calculation
            ntotal = len(l)
            chunksize = int(math.floor(ntotal / nchunks))
            nrest = ntotal % nchunks
            # calculate number of jobs for every chunk
            njob_chunk = [ chunksize for i in range(nchunks)]
            for i in range(nrest):
                njob_chunk[i] += 1

            # assign jobs for each chunk
            for i in range(nchunks):
                start_idx = sum(njob_chunk[0:i])
                end_idx = sum(njob_chunk[0:(i+1)])
                all_chunks.append(l[start_idx:end_idx])

            return all_chunks
    
     # calling in a different way 
     all_chunks = chunks(usable_stations, self.mpi.size)

```
++++++++++++++++++++++++++++++++++
The basic idea will be more easily illustrated using an example. If I have 164 streams and 16 processors, the chunksize would be 10. But there will be 4 more streams left behind. So the rest 4 more streams will be assigned to [rank0, rank,1..., rank3]. Each of them will get one  more. In this way, the job will be split into a more even way. 

As far as the errror catching for mpi4py, I have another issue in window selection that the error could't be caught. Then I have to use a brutal way to catch the error...I may discuss that with you later on.

**Comment by krischer** [comment]
Thanks for reporting this.

Yea I don't really understand my own logic there to be honest. I rewrote the whole function to be logically much simpler. Also only one core now generates the list of jobs.

I based it on this which I've been using a lot and I'm fairly sure it works as intended: https://gist.github.com/krischer/2c7b95beed642248487a
