### ISSUE TITLE
How to make pyasdf to support multi-date-range station inventory + custom tags?

### ISSUE THREAD

**Issue by zhang01GA** [SeismicData/pyasdf#61]
When I add a station XML ds.add_stationxml("multi-date-ranges.xml")
See attached xml file, 

[OA.CE22_station_inv_modified_xml.txt](https://github.com/SeismicData/pyasdf/files/4773698/OA.CE22_station_inv_modified_xml.txt)

then extracted the station xml file as shown below: There are two issues:
1) the multidate-ranges are merged into one xml node for station code="CE22".
2) our custom tagged metadata (allowed by obspy and FDSN) are lost.

Can you help by comments on these issues. Thank you!

<?xml version='1.0' encoding='UTF-8'?>
<FDSNStationXML xmlns="http://www.fdsn.org/xml/station/1" schemaVersion="1.0">
  <Source>Geoscience Australia</Source>
  <Module>ObsPy 1.0.2</Module>
  <ModuleURI>https://www.obspy.org</ModuleURI>
  <Created>2019-02-02T18:42:45</Created>
  <Network code="OA" startDate="2017-09-11T00:00:36" endDate="2018-11-28T23:06:20">
    <SelectedNumberStations>1</SelectedNumberStations>
    <Station code="CE22" startDate="2017-11-04T03:16:35" endDate="2018-11-18T20:23:20">
      <Latitude unit="DEGREES">-18.49507</Latitude>
      <Longitude unit="DEGREES">139.002731</Longitude>
      <Elevation unit="METERS">62.7</Elevation>
      <Site>
        <Name>CE22</Name>
      </Site>
      <Vault>Transportable Array</Vault>
      <CreationDate>2017-11-04T03:16:35</CreationDate>
      <TerminationDate>2018-06-06T01:02:24</TerminationDate>
      <SelectedNumberChannels>3</SelectedNumberChannels>
      <Channel code="HHZ" locationCode="0M">
        <Latitude unit="DEGREES">-18.49507</Latitude>
        <Longitude unit="DEGREES">139.002731</Longitude>
        <Elevation unit="METERS">62.7</Elevation>
        <Depth unit="METERS">0.0</Depth>
        <Azimuth unit="DEGREES">0.0</Azimuth>
        <Dip unit="DEGREES">90.0</Dip>
        <SampleRate unit="SAMPLES/S">200.0</SampleRate>
        <ClockDrift unit="SECONDS/SAMPLE">0.0</ClockDrift>
      </Channel>
      <Channel code="HHE" locationCode="0M">
        <Latitude unit="DEGREES">-18.49507</Latitude>
        <Longitude unit="DEGREES">139.002731</Longitude>
        <Elevation unit="METERS">62.7</Elevation>
        <Depth unit="METERS">0.0</Depth>
        <Azimuth unit="DEGREES">90.0</Azimuth>
        <Dip unit="DEGREES">0.0</Dip>
        <SampleRate unit="SAMPLES/S">200.0</SampleRate>
        <ClockDrift unit="SECONDS/SAMPLE">0.0</ClockDrift>
      </Channel>
      <Channel code="HHN" locationCode="0M">
        <Latitude unit="DEGREES">-18.49507</Latitude>
        <Longitude unit="DEGREES">139.002731</Longitude>
        <Elevation unit="METERS">62.7</Elevation>
        <Depth unit="METERS">0.0</Depth>
        <Azimuth unit="DEGREES">0.0</Azimuth>
        <Dip unit="DEGREES">0.0</Dip>
        <SampleRate unit="SAMPLES/S">200.0</SampleRate>
        <ClockDrift unit="SECONDS/SAMPLE">0.0</ClockDrift>
      </Channel>
    </Station>
  </Network>
</FDSNStationXML>

**Comment by krischer** [comment]
Good catch - I never really considered this. I just released `pyasdf` 0.7.0 which is more conservative when merging stations in inventory objects. I think this is a good idea in any case given that there is no good solution to this problem in general. In your particular case it means that both your problems should be resolved. Please let me know if that is not the case!

**Comment by zhang01GA** [comment]
@krischer Thank you for the clarification.

Yes I think it is very important to have our problems resolved - can you help please?

**Comment by krischer** [comment]
You are right - it was actually written to the StationXML files with `pyasdf` 0.7.0 but not in a way that could be easily accessed with ObsPy. This has been rectified with version 0.7.1 and I also added a full roundtripping integration test so it should work now!

**Comment by zhang01GA** [comment]
Excellent! Thanks a lot @krischer .
I have a quick test of pyasdf 0.7.1. And It looks working now with my problems resolved.

I will come back to you if there is any further issues. Meanwhile,  could you make it support Python=3.6.*  which is used in some of our environment?? Thanks.

**Comment by krischer** [comment]
If you want to install it on Python 3.6 for now it should be a simple case of removing the following line:

https://github.com/SeismicData/pyasdf/blob/master/setup.py#L163

I'll no longer officially support it to keep the maintenance burden down and also because the next ObsPy version will be Python >= 3.7 only. Future `pyasdf` versions will also freely use Python 3.7 features.

That being said I'd be willing to merge a pull request that adds Python 3.6 support again with the understanding that no effort will expended to retain it in the future.

**Comment by zhang01GA** [comment]
Thanks, I will try that for python 3.6. I agree we should move up with latest python.

I further tested the pyasdf 0.7.1 for my case. I extracted the stationXML files from the newly created ASDF with "extra" metadata. The output XML file (see attached below) has changed compared with the ingested XML file. And the output xml cannot be parsed correctly to get the extra metadata.

```
from obspy import read_inventory
new_station_xml="test_OA_CE22_inventory.xml"

my_inv = read_inventory(new_station_xml)
# print(inv.networks[0].stations[0].extra)

csv_str = my_inv.networks[0].stations[0].extra.gpsclockcorrection.value 
print(csv_str)
```
[test_OA_CE22_inventory.xml.txt](https://github.com/SeismicData/pyasdf/files/4786089/test_OA_CE22_inventory.xml.txt)
