### ISSUE TITLE
mpi.comm.allgather may not necessary for speed concern(not sure)

### ISSUE THREAD

**Issue by wjlei1990** [SeismicData/pyasdf#7]
Hi Lion,

In line 1267 in asdf_data_set.py:
```
 gathered_results = self.mpi.comm.allgather(results)
```

Of which I think **allgather** may not be necessary but **gather** would be enough. Two reasons:

1) at this stage, people may want just the final results. So there is no need to keep duplicates on each processors.
2) for speed concern. If people have a lot of data sitting on each processors, the **allgather** will take more time than **gather** since it needs to bcast all results.

My preference would be:
```
        gathered_results = self.mpi.comm.gather(results, root=0)
        results = {}
        if self.mpi.rank == 0:
            for result in gathered_results:
                results.update(result)
        return results
```
What do you think?

**Comment by krischer** [comment]
Good idea. If people need it on all ranks they can scatter it afterwards!
