### ISSUE TITLE
MPI can not exit

### ISSUE THREAD

**Issue by wjlei1990** [SeismicData/pyasdf#9]
Hi Lion,

I don't know if you notice it or not.

When using mpi4py.MPI and a exception(or error) was raised, but the program will just hang and quit.

I found we probably need to replace the **raise ***Error()** with something like:
```
try:
     do something here...
except Exception as exp:
     print(exp)
     MPI.COMM_WORLD.Abort()
```
Probably this is not necessary in the pyasdf code. But when we use the pyasdf module and write our own code, it is better to have this thing to prevent burning unnecessary CPU hours.

**Comment by krischer** [comment]
Yea that will happen as it cannot finalize.

Does this happen when you use the pyasdf `process()` method? That should catch all the errors if run with MPI so it should not happen there.

If it is another issue you could also try:

```python
try:
    bladiblup
finally:
    MPI.COMM_WORLD.Finalize()
```

the `finally` clause will always be called, no matter what.

**Comment by wjlei1990** [comment]
Thanks. Great suggestion :)

It is not a problem to pyasdf... I just have this issue when running programs using my own code. Just want to remind you :smile:

**Comment by krischer** [comment]
Yea that's of a pity with Python's destructors :-( I always do something like this to catch these types of errors everywhere:

```python
if __name__ == "__main__":
    try:
        main()
    finally:
        MPI.COMM_WORLD.Finalize()
```

**Comment by wjlei1990** [comment]
=.= I think we should put this issue on mpi4py :smiling_imp:
